version: '3'

services:
  nest-backend:
    container_name: nest-app
    image: nest-api
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 5000:5000
    env_file:
      - .env
    networks:
      - backend_network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
      - redis

  redis:
    container_name: redis-db
    image: redis
    env_file:
      - .env
    ports:
      - 6379:6379
    networks:
      - backend_network
    volumes:
      - redis:/data

  postgres:
    container_name: postgres-db
    image: postgres:14.5-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - backend_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    networks:
      - backend_network
    ports:
      - '5050:80'
    depends_on:
      - postgres

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data: {}
  redis:
    driver: local
